language: cpp
sudo: required
dist: trusty

compiler:
  - gcc

env:
  global:
    - secure: "C1Ai03PHHYwsJg4PXWAYheex75locrF94Fzm9esQ0NE3BaZl86Bw8hgmXFa0EKTd1Vl1vrKlqVXZg9hhPBUP4c5KyDHj5xYGWhEGLtoenLXYqCivERP5Tqq35OrFTWjWuohFvTwTMdUFbWl0r2QqZGjm/nRkQbDNWAABIPBq+4A="
    - secure: "afLxPzrM1+xjYyidIXnuAn4pimOegT5jXxQNsXXpT2Tj59odI6tL6CZuuH5/SC66E0VwcR5YnAnQ7p4OoQyysqjBApZ71fUZSTcD4r9rlOMhvRwL+6nWRPF3/WxsqWYeuHoMDit4QQR8a7WQINPnJg0ZzRjD0/bFN2j1v+vID5I="
    - secure: "cvrIzqJ8FvKXzvB4Tp8Q9gbpFfLTGkVVndrAMA6Pj0trY13nlz6Z2lg9o1Mkcmw/73ndpDImB1IhoPCrgPJBOMYrv7bOKZZJ0D6qCyoIdqspTQX7wJm0WZPQ/SqoACZjpp536AvPJ6vUdZjg+Xj2I913U7SMtvAOrBEUfbMcTOs="
    - secure: "jVA08E8NJmn4enb9Q953Ng/AW9fGVSWZaIHcBzForKPMqBCFRT15W8nDlaOfiaO4iIiN8PLPpTvzc9PuODdbZwWxaiQF2vcHSlSoKjsexJO2ay2dCH9xw7G6i5ojRniQ9aH7nHrwvf9CBZDUXDGnwmVY+xbbWEsE3sszGG/WaKU="
    - QMAKE_PARAMS="-r"
    - DEBUG=release

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - clang
      - xvfb
      - imagemagick
      - p7zip-full
      - python-pip
  coverity_scan:
    project:
      name: approximator/FlightGear_Autopilot
      version: 1.0
      description: FlightGear_Autopilot
    notification_email: alex@nls.la
    build_command_prepend: cd $TRAVIS_BUILD_DIR/src && qmake $QMAKE_PARAMS
    build_command: make
    branch_pattern: coverity_scan

before_install:
  - "export DISPLAY=:99.0"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x24"
  - sleep 3
  - sudo add-apt-repository -y ppa:beineri/opt-qt542-trusty
  - sudo add-apt-repository -y ppa:staticfloat/julia-deps

install:
  - sudo apt-get update
  - sudo pip install --upgrade pip setuptools
  - sudo pip install --upgrade httpie
  - if [ "$CXX" = "g++" ]; then sudo apt-get -y install g++-4.9; fi
  - if [ "$CXX" = "g++" ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 90; fi
  - sudo apt-get -y install qt54-meta-full patchelf

before_script:
  - echo "Before script"

  - if [ "$CXX" == "clang++" ]; then QMAKE_PARAMS="$QMAKE_PARAMS -spec linux-clang"; fi
  - if [ "$CXX" == "g++" ]; then QMAKE_PARAMS="$QMAKE_PARAMS -spec linux-g++"; fi

  - "export COMMIT_MESSAGE=\"$(git log --format=%B -n 1)\""
  - PLATFORM=$(date +"%d-%m-%Y-%H-%M")-linux-$CXX-$DEBUG-$(uname -p)
  - "export DIST_ARCHIVE=fg-autopilot-$PLATFORM.7z"
  - SCRIPTS_DIR=$TRAVIS_BUILD_DIR/scripts
  - SOURCES_DIR=$TRAVIS_BUILD_DIR/src
  - SCREENSHOT_NAME=$SOURCES_DIR/main_qml_$PLATFORM.png
  - DIST_FILE=$SOURCES_DIR/$DIST_ARCHIVE

  - source /opt/qt54/bin/qt54-env.sh
  - echo "        Compiler = $(which $CXX)"
  - echo "Compiler version = $($CXX --version)"
  - echo "   Qmake version = $(qmake -v)"
  - echo "  Httpie version = $(http --version)"
  - echo "    QMAKE_PARAMS = $QMAKE_PARAMS"
  - echo "   TRAVIS_COMMIT = $TRAVIS_COMMIT"

script:
  - if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then make ; fi
