before_install:
    - sudo add-apt-repository -y ppa:beineri/opt-qt532
    - sudo apt-get update
install:
    - sudo apt-get -y install qt53-meta-full
before_script:
    - source /opt/qt53/bin/qt53-env.sh
    - git clone git://github.com/papyros/qml-material.git
    - pushd qml-material
    - qmake
    - sudo make install
    - popd
    - git clone git://github.com/papyros/qml-extras.git
    - pushd qml-extras
    - qmake
    - sudo make install
    - popd
script:
    - source /opt/qt53/bin/qt53-env.sh
    - pwd
    - ls -lah
    - cd $TRAVIS_BUILD_DIR/src
    - pwd
    - qmake -v
    - qmake
    - make
