language: c++
env:
    global:
        # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
        #   via the "travis encrypt" command using the project repo's public key
        - secure: "K0BgqMzt8As7n0jrsUMR8zBFlennQ2UFKNR99tpL9l54Hf1cZFGNUNdDGFqCL2d1jQHXL79q0ByJMDKLe6idvuDJH3RsmuNSRZgVVtDvl1Xa1+8V0NJW7W4VOl1++7ZXIxUJ9xLP2fz26SLkH6cTCVNDKqxz5KQ7H1U66I23eBM="

addons:
    coverity_scan:
        project:
            name: "approximator/FlightGear_Autopilot"
        notification_email: alex@nls.la
        build_command_prepend: "source /opt/qt53/bin/qt53-env.sh && cd $TRAVIS_BUILD_DIR && qmake"
        build_command: "make"
        branch_pattern: master

before_install:
    - sudo add-apt-repository -y ppa:beineri/opt-qt532
    - sudo apt-get update

install:
    - sudo apt-get -y install qt53-meta-full chrpath wget

before_script:

script:
    - source /opt/qt53/bin/qt53-env.sh
    - pwd
    - ls -lah
    - cd $TRAVIS_BUILD_DIR
    - pwd
    - qmake -v
    - qmake
    - make clean
    - make
    - make deploy_all
    - cat $TRAVIS_BUILD_DIR/src/cov-int/scm_log.txt
