language: c++

env:
  global:
    - secure: "C1Ai03PHHYwsJg4PXWAYheex75locrF94Fzm9esQ0NE3BaZl86Bw8hgmXFa0EKTd1Vl1vrKlqVXZg9hhPBUP4c5KyDHj5xYGWhEGLtoenLXYqCivERP5Tqq35OrFTWjWuohFvTwTMdUFbWl0r2QqZGjm/nRkQbDNWAABIPBq+4A="
    - secure: "afLxPzrM1+xjYyidIXnuAn4pimOegT5jXxQNsXXpT2Tj59odI6tL6CZuuH5/SC66E0VwcR5YnAnQ7p4OoQyysqjBApZ71fUZSTcD4r9rlOMhvRwL+6nWRPF3/WxsqWYeuHoMDit4QQR8a7WQINPnJg0ZzRjD0/bFN2j1v+vID5I="
    - secure: "cvrIzqJ8FvKXzvB4Tp8Q9gbpFfLTGkVVndrAMA6Pj0trY13nlz6Z2lg9o1Mkcmw/73ndpDImB1IhoPCrgPJBOMYrv7bOKZZJ0D6qCyoIdqspTQX7wJm0WZPQ/SqoACZjpp536AvPJ6vUdZjg+Xj2I913U7SMtvAOrBEUfbMcTOs="

before_install:
  - sudo add-apt-repository -y ppa:beineri/opt-qt532
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update

install:
  - sudo apt-get -y install qt53-meta-full chrpath xvfb imagemagick p7zip-full g++-4.8 python-pip
  - sudo pip install --upgrade pip setuptools
  - sudo pip install --upgrade httpie
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90

before_script:
  - echo "Before script"
  - source /opt/qt53/bin/qt53-env.sh
  - echo "   GCC version =  " && gcc --version
  - echo " Qmake version =  " && qmake -v
  - echo "Httpie version =  " && http --version

script:
  - pwd
  - ls -lah
  - cd $TRAVIS_BUILD_DIR
  - pwd
  - qmake
  - make clean
  - make
  - make deploy_all
  - make bindist
  - Xvfb :5 -screen 0 1280x1024x24 -fbdir $TRAVIS_BUILD_DIR &
  - XVFB_PID=$!
  - DISPLAY=:5 $TRAVIS_BUILD_DIR/bin/fgautopilot &
  - FGAP_PID=$!
  - sleep 15
  - SCREENSHOT_NAME=$PWD/main_qml_$(date +"%d-%m-%Y-%H-%M").png
  - DISPLAY=:5 import -window root ${SCREENSHOT_NAME}
  - kill -15 $FGAP_PID
  - kill -15 $XVFB_PID
  - sleep 5
  - Xvfb :5 -screen 0 1280x1024x24 -fbdir $TRAVIS_BUILD_DIR &
  - XVFB_PID=$!
  - DISPLAY=:5 qmlscene $TRAVIS_BUILD_DIR/qml-libs/qml-fgear/demo/main.qml -I $TRAVIS_BUILD_DIR/bin/qml&
  - SCENE_PID=$!
  - sleep 10
  - SCENE_SCREENSHOT_NAME=$PWD/demo_scene_$(date +"%d-%m-%Y-%H-%M").png
  - DISPLAY=:5 import -window root ${SCENE_SCREENSHOT_NAME}
  - ls -lah
  - kill -15 $SCENE_PID
  - kill -15 $XVFB_PID
  - echo "Uploading screenshot... ($SCREENSHOT_NAME)"
  - "export COMMIT_MESSAGE=\"$(git log --format=%B --no-merges -n 1)\""
  - echo "Arti user = $ARTI_USER"
  - bash ./scripts/upload_file.sh "FlightGear_Autopilot" "$COMMIT_MESSAGE" "$SCREENSHOT_NAME" "Main window (qml)"
  - sleep 5
  - echo "Uploading SCENE screenshot... ($SCENE_SCREENSHOT_NAME) "
  - bash ./scripts/upload_file.sh "FlightGear_Autopilot" "$COMMIT_MESSAGE" "$SCENE_SCREENSHOT_NAME" "Example window"
  - DIST_FILE=$PWD/$(ls fg-autopilot*7z)
  - echo "Uploading dist file = $DIST_FILE"
  - bash ./scripts/upload_file.sh "FlightGear_Autopilot" "$COMMIT_MESSAGE" "$DIST_FILE" "Dist linux"

deploy:
  provider: releases
  api_key:
    secure: Ipvu7YEsrxax0u+JbfqlHUmfga0Sjguj3ZjUWirkSFXRmyrBzhnB+5PXubctgHHK3GrvV3uO0mq6WzPZpeNxCMKb5ymE8u8eWAWS7epE6rWVMO8IN8JzNXzISWKLDgt0Pm4lhI/LRieBhYZlAVbf8IOvCTgJfuE9K10nvfsaU1s=
  file_glob: true
  file:
    - ls "$TRAVIS_BUILD_DIR/fg-autopilot-*.7z"
    - "${SCREENSHOT_NAME}.png"
  on:
    tags: true
