language: c++

env:
  global:
    - secure: "C1Ai03PHHYwsJg4PXWAYheex75locrF94Fzm9esQ0NE3BaZl86Bw8hgmXFa0EKTd1Vl1vrKlqVXZg9hhPBUP4c5KyDHj5xYGWhEGLtoenLXYqCivERP5Tqq35OrFTWjWuohFvTwTMdUFbWl0r2QqZGjm/nRkQbDNWAABIPBq+4A="
    - secure: "afLxPzrM1+xjYyidIXnuAn4pimOegT5jXxQNsXXpT2Tj59odI6tL6CZuuH5/SC66E0VwcR5YnAnQ7p4OoQyysqjBApZ71fUZSTcD4r9rlOMhvRwL+6nWRPF3/WxsqWYeuHoMDit4QQR8a7WQINPnJg0ZzRjD0/bFN2j1v+vID5I="
    - secure: "cvrIzqJ8FvKXzvB4Tp8Q9gbpFfLTGkVVndrAMA6Pj0trY13nlz6Z2lg9o1Mkcmw/73ndpDImB1IhoPCrgPJBOMYrv7bOKZZJ0D6qCyoIdqspTQX7wJm0WZPQ/SqoACZjpp536AvPJ6vUdZjg+Xj2I913U7SMtvAOrBEUfbMcTOs="

before_install:
  - sudo add-apt-repository -y ppa:beineri/opt-qt532
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update

install:
  - sudo apt-get -y install qt53-meta-full chrpath xvfb imagemagick p7zip-full g++-4.8 python-pip
  - sudo pip install --upgrade pip setuptools
  - sudo pip install --upgrade httpie
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90

before_script:
  - echo "Before script"
  - source /opt/qt53/bin/qt53-env.sh
  - echo "   GCC version =  " && gcc --version
  - echo " Qmake version =  " && qmake -v
  - echo "Httpie version =  " && http --version

script:
  - "export COMMIT_MESSAGE=\"$(git log --format=%B --no-merges -n 1)\""
  - export DIST_ARCHIVE=fg-autopilot-linux-x86_64.7z
  - SCREENSHOT_NAME=$PWD/main_qml_$(date +"%d-%m-%Y-%H-%M").png
  - SCENE_SCREENSHOT_NAME=$PWD/demo_scene_$(date +"%d-%m-%Y-%H-%M").png
  - DIST_FILE=$PWD/$DIST_ARCHIVE
  - cd $TRAVIS_BUILD_DIR
  - pwd
  - qmake
  - make clean
  - make
  - make deploy_all
  - make bindist
  - bash ./scripts/take_screenshot.sh "$TRAVIS_BUILD_DIR/bin/fgautopilot" "${SCREENSHOT_NAME}"
  - sleep 5
  - bash ./scripts/take_screenshot.sh "qmlscene $TRAVIS_BUILD_DIR/qml-libs/qml-fgear/demo/fgap/main.qml -I $TRAVIS_BUILD_DIR/bin/qml" "${SCREENSHOT_NAME}"
  - ls -lah
  - bash ./scripts/upload_file.sh "FlightGear_Autopilot" "$COMMIT_MESSAGE" "$DIST_FILE" "Distributive linux"
  - sleep 2
  - bash ./scripts/upload_file.sh "FlightGear_Autopilot" "$COMMIT_MESSAGE" "$SCENE_SCREENSHOT_NAME" "Demo window screenshot"
  - sleep 2
  - bash ./scripts/upload_file.sh "FlightGear_Autopilot" "$COMMIT_MESSAGE" "$SCREENSHOT_NAME" "Main window screenshot (qml)"

deploy:
  provider: releases
  api_key:
    secure: "Ipvu7YEsrxax0u+JbfqlHUmfga0Sjguj3ZjUWirkSFXRmyrBzhnB+5PXubctgHHK3GrvV3uO0mq6WzPZpeNxCMKb5ymE8u8eWAWS7epE6rWVMO8IN8JzNXzISWKLDgt0Pm4lhI/LRieBhYZlAVbf8IOvCTgJfuE9K10nvfsaU1s="
  file:
    - "${DIST_FILE}"
    - "${SCREENSHOT_NAME}"
  on:
    tags: true
