language: cpp

services:
  - docker

env:
    - BUILD_VARIANT=debug
    - BUILD_VARIANT=release
    - QBS_VERSION=qbs:1.5.1.Qt5.7.1
    - QBS_VERSION=qbs:1.7.1.Qt5.7.0
    - QBS_VERSION=qbs:1.7.1.Qt5.7.1

addons:
  apt:
    packages:
      - p7zip-full
      - tree

before_script:
  - INSTALL_DIR=/tmp/fgap/docker

script:
  - ./scripts/build_in_docker.sh
  - tree -L 5 ${INSTALL_DIR}
  - docker run --rm -v ${INSTALL_DIR}:/fgap -v $PWD/contrib/Qt-Qbs-Application/scripts:/scripts approximator/qttest python /scripts/take_screenshot.py -f /fgap/install/FlightGear_Autopilot/fgautopilot -t 55 -o /fgap/install/FlightGear_Autopilot/screenshot.png
  - tree -L 5 ${INSTALL_DIR}
  - cat ${INSTALL_DIR}/install/FlightGear_Autopilot/fgautopilot.log
