language: c++

env:
  global:
    - secure: "C1Ai03PHHYwsJg4PXWAYheex75locrF94Fzm9esQ0NE3BaZl86Bw8hgmXFa0EKTd1Vl1vrKlqVXZg9hhPBUP4c5KyDHj5xYGWhEGLtoenLXYqCivERP5Tqq35OrFTWjWuohFvTwTMdUFbWl0r2QqZGjm/nRkQbDNWAABIPBq+4A="
    - secure: "afLxPzrM1+xjYyidIXnuAn4pimOegT5jXxQNsXXpT2Tj59odI6tL6CZuuH5/SC66E0VwcR5YnAnQ7p4OoQyysqjBApZ71fUZSTcD4r9rlOMhvRwL+6nWRPF3/WxsqWYeuHoMDit4QQR8a7WQINPnJg0ZzRjD0/bFN2j1v+vID5I="
    - secure: "cvrIzqJ8FvKXzvB4Tp8Q9gbpFfLTGkVVndrAMA6Pj0trY13nlz6Z2lg9o1Mkcmw/73ndpDImB1IhoPCrgPJBOMYrv7bOKZZJ0D6qCyoIdqspTQX7wJm0WZPQ/SqoACZjpp536AvPJ6vUdZjg+Xj2I913U7SMtvAOrBEUfbMcTOs="

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - h-rayflood/llvm
    packages:
      - gcc-4.8
      - g++-4.8
      - clang
      - chrpath
      - xvfb
      - imagemagick
      - p7zip-full
      - python-pip

before_install:
  - "export DISPLAY=:99.0"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x24"
  - sleep 3
  - sudo add-apt-repository -y ppa:beineri/opt-qt541

install:
  - sudo apt-get update
  - sudo pip install --upgrade pip setuptools
  - sudo pip install --upgrade httpie
  - sudo apt-get -y install qt54-meta-full
  - if [ "$CXX" = "g++" ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90; fi

before_script:
  - echo "Before script"
  - source /opt/qt54/bin/qt54-env.sh
  - echo "        Compiler = $(which $CXX)"
  - echo "Compiler version = $($CXX --version)"
  - echo "   Qmake version = $(qmake -v)"
  - echo "  Httpie version = $(http --version)"

script:
  - "export COMMIT_MESSAGE=\"$(git log --format=%B --no-merges -n 1)\""
  - "export DIST_ARCHIVE=fg-autopilot-linux-x86_64.7z"
  - SCRIPTS_DIR=$TRAVIS_BUILD_DIR/scripts
  - SOURCES_DIR=$TRAVIS_BUILD_DIR/src
  - SCREENSHOT_NAME=$SOURCES_DIR/main_qml_$(date +"%d-%m-%Y-%H-%M").png
  - SCENE_SCREENSHOT_NAME=$SOURCES_DIR/demo_scene_$(date +"%d-%m-%Y-%H-%M").png
  - DIST_FILE=$SOURCES_DIR/$DIST_ARCHIVE
  - cd $SOURCES_DIR
  - pwd
  - qmake
  - make clean
  - make -j5
  - make deploy_all
  - make bindist
  - bash $SCRIPTS_DIR/take_screenshot.sh "$SOURCES_DIR/bin/fgautopilot" "${SCREENSHOT_NAME}"
  - sleep 5
  - "ls -lah"
  - bash $SCRIPTS_DIR/upload_file.sh "FlightGear_Autopilot" "$COMMIT_MESSAGE" "$DIST_FILE" "Distributive linux"
  - sleep 2
  - sleep 2
  - bash $SCRIPTS_DIR/upload_file.sh "FlightGear_Autopilot" "$COMMIT_MESSAGE" "$SCREENSHOT_NAME" "Main window screenshot (qml)"
