language: cpp

services:
  - docker

env:
    - BUILD_VARIANT=debug
    - BUILD_VARIANT=release

addons:
  apt:
    packages:
      - p7zip-full
      - tree

before_script:
  - INSTALL_DIR=/tmp/fgap/docker

script:
  - ./scripts/build_in_docker.sh
  - tree -L 5 ${INSTALL_DIR}
  - docker run --rm -v ${INSTALL_DIR}:/fgap -v $PWD/contrib/Qt-Qbs-Application/scripts:/scripts approximator/qttest python /scripts/take_screenshot.py -f /fgap/install/FlightGear_Autopilot -t 55 -o /fgap/install/screenshot.png
  - tree -L 5 ${INSTALL_DIR}
  - cat ${INSTALL_DIR}/install/fgautopilot.log
