version: 1.0.{build}
environment:
  MINGW: C:\Qt\Tools\mingw492_32
  matrix:
  - QTDIR: C:\Qt\5.5\mingw492_32
    QMAKE_PARAMS: -r -spec win32-g++
    MAKE: mingw32-make
    DEPLOY: mingw32-make deploy_all
  - QTDIR: C:\Qt\5.5\msvc2013_64
    QMAKE_PARAMS: -r -spec win32-msvc2013 -tp vc
    MAKE: msbuild
    DEPLOY: echo "Not implemented yet"

install:
- cmd: git submodule update --init --recursive
- cmd: set PATH=%PATH%;%QTDIR%\bin;%MINGW%\bin;C:\Qt\Tools\QtCreator\bin
build_script:
- cmd: >-
    qmake src\FgAutopilot.pro %QMAKE_PARAMS%

    dir

    %MAKE%

    %DEPLOY%

artifacts:
- path: fgautopilot-0.0.3
  name: fgautopilot-0.0.3
