os: Visual Studio 2015
version: 1.0.{build}
environment:
  matrix:
  # - QTDIR: C:\Qt\5.5\mingw492_32
  #   TAKE_SCREENSHOT: scripts\take_screenshot.bat
  - QTDIR: C:\Qt\5.5\msvc2013_64
    TAKE_SCREENSHOT: echo "Not implemented yet"

install:
- cmd: git submodule update --init --recursive
- cmd: set PATH=%PATH%;%QTDIR%\bin;C:\Qt\Tools\QtCreator\bin
build_script:
- cmd: >-
    dir

    qbs setup-toolchains --detect

    qbs setup-qt --detect

    qbs setup-qt %QTDIR%\bin\qmake.exe qt

    qbs config defaultProfile qt

    cd src

    qbs --command-echo-mode command-line

    qbs --clean-install-root qbs.installRoot:fgap_install

    cd fgap_install\FlightGear_Autopilot

    windeployqt --debug fgautopilot.exe

    dir

    %TAKE_SCREENSHOT%

artifacts:
- path: src/fgap_install
  name: Flightgear Autopilot
# - path: '*.png'
#   name: screenshot
# - path: 'fgautopilot-0.0.3/*.log'
#   name: logs
